### ISSUE TITLE
Building on RPi

### ISSUE THREAD

**Issue by oori** [JeremyBYU/OrganizedPointFilters#1]
Trying to build on RPi (ARM cpu) getting this error:
```
pi@raspberrypi:~/polylidar/OrganizedPointFilters/cmake-build $ cmake --build .
Built target OrganizedPointFilters
Building CXX object src/Python/CMakeFiles/organizedpointfilters.dir/organizedpointfilters_pybind/docstring/docstring.cpp.o
c++: error: unrecognized command line option ‘-msse4.2’
make[2]: *** [src/Python/CMakeFiles/organizedpointfilters.dir/build.make:82: src/Python/CMakeFiles/organizedpointfilters.dir/organizedpointfilters_pybind/docstring/docstring.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:40807: src/Python/CMakeFiles/organizedpointfilters.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

Obviously, SSE extension isn't available on ARM.   I couldn't find where to disable this, as I only found [this comment](https://github.com/JeremyBYU/OrganizedPointFilters/blob/3824ab594d32316f4769cc0a0cffbc473e0aa7f1/include/OrganizedPointFilters/RS/DisparityTransform.hpp#L26) in your code ;)

Thanks!

**Comment by JeremyBYU** [comment]
I have an AMD cpu, zen 2 3900x. What do you have?

You can disable this here as well: https://github.com/JeremyBYU/OrganizedPointFilters/blob/b3b104c3feb2924cf7c0676693d656e9644cb8b7/src/CMakeLists.txt#L8

You will have to delete the cmake-build directory.
 Let's keep this open so I can make a cross platform change that works even on arm cpus and old x86

**Comment by JeremyBYU** [comment]
Oh sorry I saw that you said AMD but meant ARM. Should have known from title. Nevermind the question!

**Comment by oori** [comment]
Yeap, edited the original post and corrected to ARM... sorry.

**Comment by oori** [comment]
I removed `-msse4.2` and rebuilt on RPi.  it now works!   
I missed it because search "sse" or "msse" on GitHub never returned this result, only the comment I mentioned above ;(

I'll try the full monty with `polylidar-realsense` on the RPi in the next days, and update you.
thanks again!
